import isEmail from 'validator/lib/isEmail';
import isMobilePhone from 'validator/lib/isMobilePhone';
import isURL from 'validator/lib/isURL';
import isFQDN from 'validator/lib/isFQDN';
import isDate from 'validator/lib/isDate';
import isISO8601 from 'validator/lib/isISO8601';
import { marked } from 'marked';

import { markdown } from './markdown';
import { ISODateString, ISOString } from './epoch';

//
// Utilities (static) functions, to support IDEA's projects.
//

/**
 * Get the ISO string version of a date in the format `YYYY-MM-DDTHH:mm:ss.sssZ`.
 * The timezone is always UTC, as denoted by the suffix `Z`.
 */
export const toISOString = (input: Date | number | ISOString | ISODateString): ISOString | null => {
  if (!input) return null;
  const date = input instanceof Date ? input : new Date(input);
  return date.toISOString();
};
/**
 * Get the current date and time in the format `YYYY-MM-DDTHH:mm:ss.sssZ`.
 * The timezone is always UTC, as denoted by the suffix `Z`.
 */
export const nowISOString = (): ISOString => toISOString(new Date());

/**
 * Get the ISO string version of a date in the format `YYYY-MM-DD`.
 * It doesn't say anything about the timezone.
 */
export const toISODateString = (input: Date | number | ISOString | ISODateString): ISODateString | null => {
  if (!input) return null;
  // convert an ISODateString in an ISOstring
  if (typeof input === 'string' && input.match(/^\d{4}-\d{2}-\d{2}$/)) input += 'T12:00:00.000Z';
  // it forces the internal time to 12.00 to make the date timezone-resistant
  const dateResistantToTimeZones = new Date(input);
  dateResistantToTimeZones.setHours(12, 0, 0, 0);
  return dateResistantToTimeZones.toISOString().slice(0, 10);
};
/**
 * @deprecated use toISODateString instead
 */
export const toISODate = toISODateString;
/**
 * Get the current date in the format `YYYY-MM-DD`.
 * It doesn't say anything about the timezone.
 */
export const nowISODateString = (): ISODateString => toISODateString(new Date());

/**
 * Clean a string to use it within filenames and so.
 * @param str the string to clean
 * @param separator optional, separator char
 * @returns cleaned string
 */
export const cleanStr = (str: string, separator?: string): string =>
  (str ?? '').toLowerCase().replace(/[^a-zA-Z0-9]+/g, separator ?? '');

/**
 * Join two arrays by a common column, selecting which data to extract.
 * @param mainTable the main array
 * @param lookupTable the lookup array
 * @param mainKey mainTable's column for the join condition
 * @param lookupKey lookupTable's column for the join condition
 * @param selectFunction defines which
 * attributes we want to retain in the joined array; null values generated by the
 * function are ignored
 * @returns the joined array
 */
export const joinArraysOnKeys = (
  mainTable: any[],
  lookupTable: any[],
  mainKey: string,
  lookupKey: string,
  selectFunction: (attrMainTable: string, attrLookupTable: string) => any[]
): any[] => {
  const lookupIndex = [];
  const output = [];
  for (const row of lookupTable) lookupIndex[row[lookupKey]] = row;
  for (const row of mainTable) {
    const lookupTableRow = lookupIndex[row[mainKey]];
    const outputElement = selectFunction(row, lookupTableRow);
    if (outputElement) output.push(outputElement);
  }
  return output;
};

/**
 * Check if a field (/variable) is empty or invalid, based on its type.
 * If the type isn't passed as a parameter, it will be auto-detected.
 *
 * A field is "empty" when it carries no usable value; the check is intentionally
 * fail-closed: when in doubt (wrong runtime type, unexpected exception) it returns `true`.
 * The supported `fieldType` values:
 *  - `string`: not a string, or only whitespace.
 *  - `number`: not a finite number (`NaN`/`±Infinity`/non-numbers included), or `0`.
 *  - `positiveNumber`: not a finite number, or `<= 0`.
 *  - `integer`: not an integer, or `0`.
 *  - `positiveInteger`: not an integer, or `<= 0`.
 *  - `boolean`: not a boolean — both `true` and `false` are valid, non-empty values.
 *  - `object`: an empty array/Set/plain object, or an invalid `Date`.
 *  - `date`: not a strict, calendar-valid `YYYY-MM-DD` string (see `ISODateString`).
 *  - `datetime`: not a complete ISO 8601 date-time string (see `ISOString`); a date-only
 *     string such as `2026-05-22` is considered empty here — use `date` for that.
 *  - `email` / `phone` / `url` / `domain`: not a string, or not valid for the format.
 *
 * @param field the field to check
 * @param fieldType set to force a type check
 * @returns return if the field is empty/invalid or not
 */
export const isEmpty = (field: any, fieldType?: isEmptyFieldTypes): boolean => {
  if (field === null || field === undefined) return true;
  const type = fieldType ?? typeof field;
  if (!type) return true;
  try {
    switch (type) {
      case 'string':
        return typeof field !== 'string' || !field.trim().length;
      case 'number':
        return !Number.isFinite(field) || field === 0;
      case 'positiveNumber':
        return !Number.isFinite(field) || field <= 0;
      case 'integer':
        return !Number.isInteger(field) || field === 0;
      case 'positiveInteger':
        return !Number.isInteger(field) || field <= 0;
      case 'boolean':
        return typeof field !== 'boolean';
      case 'object':
        if (field instanceof Array) return field.length <= 0;
        else if (field instanceof Set) return field.size <= 0;
        else if (field instanceof Date) return Number.isNaN(field.getTime());
        else return Object.keys(field).length <= 0;
      case 'date':
        return (
          typeof field !== 'string' || !isDate(field, { format: 'YYYY-MM-DD', strictMode: true, delimiters: ['-'] })
        );
      case 'datetime':
        return typeof field !== 'string' || !field.includes('T') || !isISO8601(field, { strict: true });
      case 'email':
        return typeof field !== 'string' || !isEmail(field);
      case 'phone':
        return typeof field !== 'string' || !isMobilePhone(field, 'any');
      case 'url':
        return typeof field !== 'string' || !isURL(field);
      case 'domain':
        return typeof field !== 'string' || !isFQDN(field, { require_tld: false });
      default:
        return true;
    }
  } catch (_) {
    return true;
  }
};
export type isEmptyFieldTypes =
  | 'string'
  | 'number'
  | 'positiveNumber'
  | 'integer'
  | 'positiveInteger'
  | 'boolean'
  | 'object'
  | 'date'
  | 'datetime'
  | 'email'
  | 'phone'
  | 'url'
  | 'domain';

/**
 * Convert a markdown string to HTML.
 */
export const mdToHtml = (mdString: markdown | string): string =>
  !mdString ? '' : (marked(mdString, { gfm: true, breaks: true }) as string);

//
// DEPRECATED
//

/**
 * @deprecated Get an array to iterate containing the keys of a string enum.
 */
export const loopStringEnumKeys = (theEnum: any): string[] => Object.keys(theEnum);
/**
 * @deprecated Get an array to iterate containing the values of a string enum.
 */
export const loopStringEnumValues = (theEnum: any): string[] => Object.keys(theEnum).map(key => theEnum[key]);
/**
 * @deprecated Get an array to iterate containing the keys of a numeric enum.
 */
export const getStringEnumKeyByValue = (theEnum: any, value: string): string => {
  const el = Object.keys(theEnum)
    .map(key => ({ value: theEnum[key], key }))
    .find(x => x.value === value);
  return el ? el.key : null;
};
/**
 * @deprecated Get an array to iterate containing the keys of a numeric enum.
 */
export const loopNumericEnumKeys = (theEnum: any): number[] =>
  Object.keys(theEnum)
    .filter(key => !isNaN(Number(key)))
    .map(c => Number(c));
/**
 * @deprecated Get an array to iterate containing the values of a numeric enum.
 */
export const loopNumericEnumValues = (theEnum: any): string[] =>
  Object.keys(theEnum)
    .filter(key => !isNaN(Number(theEnum[key])))
    .map(c => String(c));
